# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181111_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('prse', models.IntegerField()),
                ('goodsname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(unique=True),
        ),
    ]
