# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
